version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1211
      MYSQL_DATABASE: beepdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: